### ISSUE TITLE
Feature: Increment SYSID_THISMAV on each platform

### ISSUE THREAD

**Issue by radarku** [radarku/sitl-swarm#1]
According to

http://ardupilot.org/copter/docs/parameters.html

`SYSID_THISMAV` Allows setting an individual MAVLink system id for this vehicle to distinguish it from others on the same network.  Setting this should let us use multi-connection enabled GCS to display/control each SITL instance separately.

**Comment by gitdillo** [comment]
Yup, I just came along your image and that is, indeed a problem. When you spawn each instance, SYSID_THISMAV should be incremented, just as you with latitude and longitude. The current version is unusable with a GCS.
It seems that the instances are reading "/copter/Tools/autotest/default_params/copter.parm"
Perhaps before spawning the instances, you could copy copter.parm, insert the appropriate SYSID_THISMAV and then use this file instead of the default "copter.parm".

**Comment by radarku** [comment]
implemented in https://github.com/radarku/sitl-swarm/tree/feature/1-increment-sysid_thismav-on-each-platform
